name: Build & Push Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/build-frontend.yml'
  workflow_dispatch:  # <-- adds manual trigger
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: indikaeranga06
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: indikaeranga06/frontend:latest
