name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 10m
          script: |
            # Pull latest images
            docker pull indikaeranga06/book-crd-frontend:${{ github.event.inputs.tag || 'latest' }}
            docker pull indikaeranga06/book-crd-backend:${{ github.event.inputs.tag || 'latest' }}

            # Stop and remove old containers if they exist
            docker stop frontend || true
            docker rm frontend || true
            docker stop backend || true
            docker rm backend || true

            # Run new containers
            docker run -d -p 5173:80 --name frontend indikaeranga06/book-crd-frontend:${{ github.event.inputs.tag || 'latest' }}
            docker run -d -p 3030:3030 --name backend indikaeranga06/book-crd-backend:${{ github.event.inputs.tag || 'latest' }}
